### ISSUE TITLE
the documentation is not clear enough, and it is hard to replicate the results.

### ISSUE THREAD

**Issue by shijing001** [jiasenlu/vilbert_beta#34]
For the VCR project, can you show us how to organize the data/VCR folder.
I've tried to organize this folder many times in different ways, but I got errors each time.

In the vlbert.yml file, you claim 
features_h5path1: data/VCR/VCR_resnet101_faster_rcnn_genome.lmdb
features_h5path2: data/VCR/VCR_gt_resnet101_faster_rcnn_genome.lmdb

I got the error: c
Traceback (most recent call last):
  File "eval_tasks.py", line 228, in <module>
    main()
  File "eval_tasks.py", line 169, in main
    = LoadDatasetEval(args, task_cfg, args.tasks.split('-'))
  File "/hpchome/carin/ss1043/vilbert_beta/vilbert/task_utils.py", line 279, in
    args.in_memory)
  File "/hpchome/carin/ss1043/vilbert_beta/vilbert/datasets/_image_features_rea
    lock=False, readahead=False, meminit=False)
lmdb.Error: data/VCR/VCR_resnet101_faster_rcnn_genome.lmdb: Not a directory

In the dropbox data folder: 
https://www.dropbox.com/sh/9pgxc3njd3iq03o/AADXgnT1HmEdrds7aujTncBGa?dl=0
If i organize data this way, I got another error:
Traceback (most recent call last):
  File "eval_tasks.py", line 228, in <module>
    main()
  File "eval_tasks.py", line 169, in main
    = LoadDatasetEval(args, task_cfg, args.tasks.split('-'))
  File "/hpchome/carin/ss1043/vilbert_beta/vilbert/task_utils.py", line 283, in LoadDatasetEval
    task_feature_reader2[features_h5path] = ImageFeaturesH5Reader(features_h5path, args.in_memory)
  File "/hpchome/carin/ss1043/vilbert_beta/vilbert/datasets/_image_features_reader.py", line 43, in __init__
    lock=False, readahead=False, meminit=False)
lmdb.InvalidError: data/VCR/VCR_gt_resnet101_faster_rcnn_genome.lmdb: MDB_INVALID: File is not an LMDB file

**Comment by martiansideofthemoon** [comment]
Any update on this? I'm facing the same issue with Flickr30k

**Comment by 201528014227051** [comment]
> Any update on this? I'm facing the same issue with Flickr30k

you are not alone
