### ISSUE TITLE
lmdb.CorruptedError: mdb_get: MDB_CORRUPTED: Located page was wrong type

### ISSUE THREAD

**Issue by Tclz** [jiasenlu/vilbert_beta#59]
When i download the feature file data.mdb(58.7G) in VCR project, and run the eval_tasks.py, i meet the following errors.
Traceback (most recent call last):
  File "eval_tasks.py", line 231, in <module>
    main()
  File "eval_tasks.py", line 172, in main
    = LoadDatasetEval(args, task_cfg, args.tasks.split('-'))
  File "/home/vilbert_beta/vilbert/task_utils.py", line 283, in LoadDatasetEval
    args.in_memory)
  File "/home/vilbert_beta/vilbert/datasets/_image_features_reader.py", line 47, in __init__
    **self._image_ids = pickle.loads(txn.get('keys'.encode()))
lmdb.CorruptedError: mdb_get: MDB_CORRUPTED: Located page was wrong type**

I don't know what's wrong with the .mdb files and please tell me how to fix it. 
Thanks in advance!!

**Comment by HarveyGuo960817** [comment]
> When i download the feature file data.mdb(58.7G) in VCR project, and run the eval_tasks.py, i meet the following errors.
> Traceback (most recent call last):
> File "eval_tasks.py", line 231, in
> main()
> File "eval_tasks.py", line 172, in main
> = LoadDatasetEval(args, task_cfg, args.tasks.split('-'))
> File "/home/vilbert_beta/vilbert/task_utils.py", line 283, in LoadDatasetEval
> args.in_memory)
> File "/home/vilbert_beta/vilbert/datasets/_image_features_reader.py", line 47, in **init**
> **self._image_ids = pickle.loads(txn.get('keys'.encode())) lmdb.CorruptedError: mdb_get: MDB_CORRUPTED: Located page was wrong type**
> 
> I don't know what's wrong with the .mdb files and please tell me how to fix it.
> Thanks in advance!!

+1
